package view;

import controller.Gestore;
import model.Auto;
import model.Furgone;
import model.Veicolo;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 * Main application window.
 * Displays the vehicle list and delegates all logic to {@link controller.Gestore}.
 *
 * @author samuf
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    // il Gestore è condiviso con ModificaCatalogo
    private Gestore g = new Gestore();

    /**
     * Initializes the form and registers all missing action listeners.
     */
    public MainFrame() {
        initComponents();
        jTable1.getTableHeader().setReorderingAllowed(false);

        jMenuItem2.addActionListener(e -> g.salva());
        jMenuItem3.addActionListener(e -> g.salvaConNome());

        jButton2.addActionListener(e -> {
            Veicolo sel = getVeicoloSelezionato();
            if (sel == null) { g.NessunaSelezione(); return; }
            if (g.confermaEliminazione()) {
                g.removeVeicolo(sel);
                aggiornaTabella();
            }
        });

        jMenuItem6.addActionListener(e -> apriModifica(null));

        jMenuItem7.addActionListener(e -> {
            Veicolo sel = getVeicoloSelezionato();
            if (sel == null) { g.NessunaSelezione(); return; }
            if (g.confermaEliminazione()) {
                g.removeVeicolo(sel);
                aggiornaTabella();
            }
        });

        jMenuItem8.addActionListener(e -> {
            Veicolo sel = getVeicoloSelezionato();
            if (sel == null) { g.NessunaSelezione(); return; }
            apriModifica(sel);
        });

        jMenuItem9.addActionListener(e -> g.visualizzaLista());
        jMenuItem5.addActionListener(e -> g.about());
        jMenuItem10.addActionListener(e -> g.credits());

        jButton1.addActionListener(e -> {
            String targa = jTextField1.getText();
            String tipo  = (String) jComboBox1.getSelectedItem();
            riempiTabella(g.cerca(targa, tipo));
        });
    }

    /**
     * Refreshes the table with the full vehicle list from the Gestore.
     */
    public void aggiornaTabella() {
        riempiTabella(g.getVeicoli());
    }

    /**
     * Returns the shared Gestore instance.
     *
     * @return the Gestore
     */
    public Gestore getGestore() {
        return g;
    }

    /**
     * Returns the vehicle matching the selected table row, or null if none selected.
     */
    private Veicolo getVeicoloSelezionato() {
        int riga = jTable1.getSelectedRow();
        if (riga == -1) return null;
        String targa = (String) jTable1.getValueAt(riga, 0);
        return g.getPerTarga(targa);
    }

    /**
     * Fills the table with the given vehicle list.
     *
     * @param lista list of vehicles to display
     */
    private void riempiTabella(ArrayList<Veicolo> lista) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Veicolo v : lista) {
            String tipo = (v instanceof Auto) ? "Automobile" : "Furgone";
            model.addRow(new Object[]{
                v.getTarga(), tipo, v.getMarca(), v.getModello(),
                v.getAnno(), v.getKm(),
                v.getScadenzaAssicurazione(),
                v.getScadenzaRevisione(),
                v.getScadenzaTagliando(),
                v.getClasseEnergetica(),
                v.getConsumo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 500));

        jLabel1.setText("Cerca per targa:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tutti", "Automobile", "Furgone" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel2.setText("Tipo:");

        jButton1.setText("Cerca");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Targa", "Tipo", "Marca", "Modello", "Anno", "Km", "Scad. Assicurazione", "Scad. Revisione", "Scad. Tagliando", "Classe Energ.", "Consumo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Elimina");

        jButton3.setText("Modifica");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Inserisci");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jMenu1.setText("File");

        jMenuItem1.setText("Apri");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salva");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salva con nome");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Esci");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("Inserisci");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Elimina");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Modifica");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Visualizza Lista");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Info");

        jMenuItem5.setText("About");
        jMenu3.add(jMenuItem5);

        jMenuItem10.setText("Credits");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(339, 339, 339)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens the edit/insert window.
     *
     * @param v vehicle to edit, or null for a new insertion
     */
    private void apriModifica(Veicolo v) {
        ModificaCatalogo popUp = new ModificaCatalogo(g, this, v);
        popUp.setLocationRelativeTo(this);
        popUp.setVisible(true);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String targa = jTextField1.getText();
        String tipo  = (String) jComboBox1.getSelectedItem();
        riempiTabella(g.cerca(targa, tipo));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Veicolo sel = getVeicoloSelezionato();
        if (sel == null) { g.NessunaSelezione(); return; }
        apriModifica(sel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        apriModifica(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        g.apri();
        aggiornaTabella();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        g.esci();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * Application entry point.
     *
     * @param args command line arguments (unused)
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
