package view;

import controller.Gestore;
import model.Veicolo;
import model.Auto;
import model.Furgone;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Insert/edit window for a single vehicle.
 * Collects field values and delegates all logic to {@link controller.Gestore}.
 *
 * @author samuf
 */
public class ModificaCatalogo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificaCatalogo.class.getName());

    // attributi per i campi auto o furgone da inserire
    private JPanel panAuto;
    private JPanel panFurgone;
    private JTextField posti, tipoAuto, velMax, colore;
    private JTextField fVolume, fAutonomia;

    // riferimenti passati da MainFrame
    private Gestore g;
    private MainFrame mainFrame;
    private Veicolo veicoloInModifica; // null = inserimento, non-null = modifica

    /**
     * @param g                 shared Gestore instance
     * @param mainFrame         main window reference (to refresh the table)
     * @param veicoloInModifica vehicle to edit, or null for a new insertion
     */
    public ModificaCatalogo(Gestore g, MainFrame mainFrame, Veicolo veicoloInModifica) {
        this.g = g;
        this.mainFrame = mainFrame;
        this.veicoloInModifica = veicoloInModifica;

        initComponents();

        panContenitore.setLayout(new BorderLayout());
        creaPanAuto();
        creaPanFurgone();
        comboTipo.addActionListener(e -> aggiorna());
        aggiorna();

        // se siamo in modalità modifica, pre-popola i campi
        if (veicoloInModifica != null) {
            prePopola();
        }
    }

    /** Pre-fills all fields with the values of the vehicle being edited. */
    private void prePopola() {
        Veicolo v = veicoloInModifica;

        Targa.setText(v.getTarga());
        Targa.setEditable(false); // la targa non si può cambiare
        marca.setText(v.getMarca());
        modello.setText(v.getModello());
        anno.setText(String.valueOf(v.getAnno()));
        km.setText(String.valueOf(v.getKm()));
        assicurazione.setText(v.getScadenzaAssicurazione().toString());
        revisione.setText(v.getScadenzaRevisione().toString());
        tagliando.setText(v.getScadenzaTagliando().toString());
        classeEnergetica.setText(v.getClasseEnergetica());
        consumo.setText(String.valueOf(v.getConsumo()));

        if (v instanceof Auto) {
            comboTipo.setSelectedItem("Auto");
            aggiorna();
            Auto a = (Auto) v;
            posti.setText(String.valueOf(a.getPosti()));
            tipoAuto.setText(a.getTipo());
            velMax.setText(String.valueOf(a.getvMax()));
            colore.setText(a.getColore());
        } else if (v instanceof Furgone) {
            comboTipo.setSelectedItem("Furgone");
            aggiorna();
            Furgone f = (Furgone) v;
            fVolume.setText(String.valueOf(f.getVolume()));
            fAutonomia.setText(String.valueOf(f.getAutonomia()));
        }
    }

    /** Collects field values, calls Gestore.inserisci() or Gestore.modifica(), then closes on success. */
    private void eseguiConferma() {
        String[] dati;

        if ("Auto".equals(comboTipo.getSelectedItem())) {
            dati = new String[]{
                Targa.getText(), marca.getText(), modello.getText(),
                anno.getText(), km.getText(),
                assicurazione.getText(), revisione.getText(), tagliando.getText(),
                classeEnergetica.getText(), consumo.getText(),
                posti.getText(), tipoAuto.getText(), velMax.getText(), colore.getText()
            };
        } else {
            dati = new String[]{
                Targa.getText(), marca.getText(), modello.getText(),
                anno.getText(), km.getText(),
                assicurazione.getText(), revisione.getText(), tagliando.getText(),
                classeEnergetica.getText(), consumo.getText(),
                fVolume.getText(), fAutonomia.getText()
            };
        }

        boolean ok;
        if (veicoloInModifica == null) {
            ok = g.inserisci(dati);
        } else {
            ok = g.modifica(veicoloInModifica, dati);
        }

        if (ok) {
            mainFrame.aggiornaTabella(); // aggiorna la JTable nel MainFrame
            this.dispose();              // chiude questa finestra
        }
        // se ok è false il Gestore ha già mostrato un messaggio di errore
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Targa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        modello = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        assicurazione = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        revisione = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        km = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tagliando = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        classeEnergetica = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        consumo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        panContenitore = new javax.swing.JPanel();
        conferma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 750));

        Targa.addActionListener(this::TargaActionPerformed);
        jLabel1.setText("Targa");

        marca.addActionListener(this::marcaActionPerformed);
        jLabel2.setText("Marca");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Furgone" }));
        comboTipo.addActionListener(this::comboTipoActionPerformed);

        modello.addActionListener(this::modelloActionPerformed);
        jLabel3.setText("Modello");

        anno.addActionListener(this::annoActionPerformed);
        jLabel4.setText("Anno");

        assicurazione.addActionListener(this::assicurazioneActionPerformed);
        jLabel5.setText("Scadenza assicurazione");

        revisione.addActionListener(this::revisioneActionPerformed);
        jLabel6.setText("Scadenza revisione");

        km.addActionListener(this::kmActionPerformed);
        jLabel7.setText("Km");

        tagliando.addActionListener(this::tagliandoActionPerformed);
        jLabel8.setText("Scadenza tagliando");

        classeEnergetica.addActionListener(this::classeEnergeticaActionPerformed);
        jLabel9.setText("Classe energetica");

        consumo.addActionListener(this::consumoActionPerformed);
        jLabel10.setText("Consumo (L/100km)");

        javax.swing.GroupLayout panContenitoreLayout = new javax.swing.GroupLayout(panContenitore);
        panContenitore.setLayout(panContenitoreLayout);
        panContenitoreLayout.setHorizontalGroup(
            panContenitoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        panContenitoreLayout.setVerticalGroup(
            panContenitoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        conferma.setText("Conferma");
        conferma.addActionListener(this::confermaActionPerformed);

        jButton1.setText("Annulla");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conferma)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(152, 152, 152))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(57, 57, 57)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modello, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tagliando, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assicurazione, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(revisione, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(152, 152, 152)
                                    .addComponent(Targa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(classeEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panContenitore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Targa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assicurazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revisione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagliando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classeEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContenitore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conferma)
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );

        getAccessibleContext().setAccessibleDescription("");
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creaPanAuto() {
        panAuto = new JPanel(new GridLayout(0, 2, 5, 5));

        panAuto.add(new JLabel("Posti"));
        posti = new JTextField();
        panAuto.add(posti);

        panAuto.add(new JLabel("Tipo"));
        tipoAuto = new JTextField();
        panAuto.add(tipoAuto);

        panAuto.add(new JLabel("Velocità max"));
        velMax = new JTextField();
        panAuto.add(velMax);

        panAuto.add(new JLabel("Colore:"));
        colore = new JTextField();
        panAuto.add(colore);
    }

    private void creaPanFurgone() {
        panFurgone = new JPanel(new GridLayout(0, 2, 5, 5));

        panFurgone.add(new JLabel("Volume:"));
        fVolume = new JTextField();
        panFurgone.add(fVolume);

        panFurgone.add(new JLabel("Autonomia:"));
        fAutonomia = new JTextField();
        panFurgone.add(fAutonomia);
    }

    private void aggiorna() {
        panContenitore.removeAll();
        if ("Auto".equals(comboTipo.getSelectedItem())) {
            panContenitore.add(panAuto, BorderLayout.CENTER);
        } else {
            panContenitore.add(panFurgone, BorderLayout.CENTER);
        }
        panContenitore.revalidate();
        panContenitore.repaint();
    }

    private void TargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TargaActionPerformed
    }//GEN-LAST:event_TargaActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
    }//GEN-LAST:event_marcaActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
    }//GEN-LAST:event_comboTipoActionPerformed

    private void modelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelloActionPerformed
    }//GEN-LAST:event_modelloActionPerformed

    private void annoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annoActionPerformed
    }//GEN-LAST:event_annoActionPerformed

    private void assicurazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assicurazioneActionPerformed
    }//GEN-LAST:event_assicurazioneActionPerformed

    private void revisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisioneActionPerformed
    }//GEN-LAST:event_revisioneActionPerformed

    private void kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmActionPerformed
    }//GEN-LAST:event_kmActionPerformed

    private void tagliandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagliandoActionPerformed
    }//GEN-LAST:event_tagliandoActionPerformed

    private void classeEnergeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classeEnergeticaActionPerformed
    }//GEN-LAST:event_classeEnergeticaActionPerformed

    private void consumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumoActionPerformed
    }//GEN-LAST:event_consumoActionPerformed

    private void confermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaActionPerformed
        eseguiConferma();
    }//GEN-LAST:event_confermaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Stand-alone entry point for previewing this form.
     *
     * @param args command line arguments (unused)
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new ModificaCatalogo(new Gestore(), null, null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Targa;
    private javax.swing.JTextField anno;
    private javax.swing.JTextField assicurazione;
    private javax.swing.JTextField classeEnergetica;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton conferma;
    private javax.swing.JTextField consumo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField km;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modello;
    private javax.swing.JPanel panContenitore;
    private javax.swing.JTextField revisione;
    private javax.swing.JTextField tagliando;
    // End of variables declaration//GEN-END:variables
}
